### ISSUE TITLE
Trocar " " por "_" ao pegar o nome dos monitores e medidores

### ISSUE THREAD

**Issue by whysofast** [dbarbosa0/sipla#32]
- [ ] Quando o elemento é criado com um nome composto ele fica assim : "New EnergyMeter.**Rec teste** Element=Recloser.w71766 Terminal=1", não sei se buga, mas pode ser que sim

**Comment by whysofast** [comment]
Bastaria adicionar um ".replace(" ", "_") na string coletada.

**Comment by Sandyaquino** [comment]
Neste caso o elemento se chamaria apenas Rec. Talvez funcione com um warning, porém sua sugestão uma solução viável.
