### ISSUE TITLE
Dispositivos da classe proteção não são filtrados a partir dos alimentadores selecionados, somente pela subestação.

### ISSUE THREAD

**Issue by whysofast** [dbarbosa0/sipla#48]
Ao exibir os elementos e barras, são listados todos os dispositivos, e não somente aqueles referentes ao(s) alimentador(es) selecionados.

**Comment by whysofast** [comment]
![image](https://user-images.githubusercontent.com/39545472/87440644-9577aa00-c5c8-11ea-8daa-bca005fbc83b.png)

**Comment by whysofast** [comment]
Resolvido no branch "Carvalho", no arquivo /opendss/class_data com esta estrutura 
![image](https://user-images.githubusercontent.com/39545472/88706935-e965b100-d0e7-11ea-90c7-31fa2db8ea71.png) nos 4 casos do if elif elif else do método **getSEC_Control**

**Comment by whysofast** [comment]
![image](https://user-images.githubusercontent.com/39545472/88722658-01e0c600-d0fe-11ea-8646-93e1cb18a29e.png)

**Comment by dbarbosa0** [comment]
Já realizei o merge com o meu branch
